### ISSUE TITLE
I have a doubt about one of the lines in the file

### ISSUE THREAD

**Issue by justinjk007** [flexibeast/emacs-bug-reporting#2]
> If the problem continues to present, even when not loading your personal configuration, then a package you've installed might be the problem.

How does the installed package affect Emacs when we are not loading the init file ?

**Comment by flexibeast** [comment]
Oops, nice catch, thanks! i think that's a leftover from an earlier draft ....

**Comment by justinjk007** [comment]
Oh So  I was right then.

**Comment by flexibeast** [comment]
You were, indeed. :-) i've now [changed the text](https://github.com/flexibeast/emacs-bug-reporting/commit/68fd164bb750cbea047c3d5576fa505c00186988). Thanks again!
