### ISSUE TITLE
2nd Footnote referent is missing.

### ISSUE THREAD

**Issue by jasonhemann** [flexibeast/emacs-bug-reporting#3]
https://github.com/flexibeast/emacs-bug-reporting/blob/61bad0d25e331bebf30d56c19b709dc64eae283c/README.md?plain=1#L47

**Comment by flexibeast** [comment]
Thanks for the heads-up! The problem was that both references in the text were labelled as "[1]". i've now fixed that, and moved this document across to my [guides repo](https://github.com/flexibeast/guides/).
